### ISSUE TITLE
Это SDK только для работы на сервере?

### ISSUE THREAD

**Issue by Fi1osof** [Tinkoff/invest-js#18]
Судя по всему, @grpc/grpc-js предназначен только для работы на стороне сервера, ибо юзает модуль fs. 
пожалуйста, напишите в описании, что это не работает на стороне фронта. Это очень важный момент и сильно влияет на архитектуру и стратегию. Задача стояла в том, чтобы заюзать стримы на стороне браузера (чтобы отдельные соединения были для каждого пользователя в отдельности, по разным причинам, включая ограничения на один ip). А тут нет, нельзя такого.

**Comment by ZigGreen** [comment]
Привет. Пока поддерживается node js только. В дальнейшем будем расширять поддержку на deno и запуск во всех популярных браузерах. 

А можно юзкейс подробнее? Может запланируем изменения, чтоб удовлетворить ваши потребности.

**Comment by Fi1osof** [comment]
> Привет. Пока поддерживается node js только. В дальнейшем будем расширять поддержку на deno и запуск во всех популярных браузерах.
> 
> А можно юзкейс подробнее? Может запланируем изменения, чтоб удовлетворить ваши потребности.

Привет.
Я хочу сделать веб-вьюху для нескольких пользователей. Соответственно, мне нужны и риал-тайм данные. В текущей реализации я должен проксировать через свой сервер такие соединения (то есть из браузера направлять на свой сервер запрос и там его уже поднимать соединение до вас). Но это, во-первых, усложняет архитектуру, во-вторых, на вашей стороне есть ограничения на кол-во запросов с одного ip (а в данном случае вы будете видеть именно мой ip сервера, а не конечного пользователя). Вот и получается, у каждого свой токет и свои лимиты, а в итоге единые лимиты на всех, еще и необходимость слать на мой сервер токен пользователя.

Так же пробовал на старый API поднимать прямое соединение через WebSocket, но там получаю CORS. То есть пока в плане соединения напрямую из браузера все очень грустно.
